package accounts;

import java.util.List;

/**
 * Provides an autogenerated account number every time an instance is created.
 * @author Mihut Balasanu
 */
public class AccountNumber {

    /**
     * Field that ensures an increment for any new account number
     */
    private static Long count = 1L;

    /**
     * Every new instance will determine an increment of 1 for the field
     */
    public AccountNumber(){
        count = getCount();
       count++;
    }

    /**
     * Generates an account number every time is invoked
     * @return A string containing a new account number for the account that invoke the method
     */
    public String generateAccountNumber(){
        String accountNumber = "RO25BCRY3400SV";
        Long number = new Long(1000000000);
        number = number + count;
        accountNumber = accountNumber.concat(String.valueOf(number));
        return accountNumber;
    }

    /**
     * Counts the number of all the accounts already created and written in the "account details.txt" file
     * @return A long containing the number of all accounts already created by all users
     */
    public Long getCount(){
        AccountFileReader accountFileReader = new AccountFileReader();
        List<Account> accounts = accountFileReader.getAccounts();
        for (Account account : accounts) {
            count++;
            }
        return count;
        }
    }

